name: quoterer
services:
    bot:
        container_name: quoterer-bot
        build: .
        depends_on:
            - database
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
            DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
            DISCORD_TOKEN: ${DISCORD_TOKEN}
            SALT: ${SALT}
        networks:
            - quoterer-network
    database:
        container_name: quoterer-db
        image: postgres:alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - quoterer-network

volumes:
    postgres-data:

networks:
    quoterer-network:
        driver: bridge
