name: quoterer
services:
  bot:
    container_name: quoterer-bot
    build: ./bot
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file: ".env"
    environment:
      db_uri: mongodb://${db_user}:${db_password}@mongo:27017/
      bot_id: ${bot_id}
      bot_token: ${bot_token}
    networks:
      - quoterer-network

  mongo:
    container_name: quoterer-mongo
    image: mongo
    restart: unless-stopped
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${db_user}
      MONGO_INITDB_ROOT_PASSWORD: ${db_password}
    volumes:
      - "./db/data:/data/db"
    networks:
      - quoterer-network

  mongo-express:
    container_name: quoterer-mongo-express
    image: mongo-express
    depends_on:
    - mongo
    restart: unless-stopped
    ports:
      - 8081:8081
    env_file: ".env"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${db_user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${db_password}
      ME_CONFIG_MONGODB_URL: mongodb://${db_user}:${db_password}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${db_interface_user}
      ME_CONFIG_BASICAUTH_PASSWORD: ${db_interface_password}
      ME_CONFIG_BASICAUTH: true
    networks:
      - quoterer-network
      
networks:
  quoterer-network:
    driver: bridge
