name: quote-gatherer
services:
  mongo:
    image: mongo
    restart: always
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${db_user}
      MONGO_INITDB_ROOT_PASSWORD: ${db_password}
    ports:
      - 27017:27017
    volumes:
      - "./db/data:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: ".env"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${db_user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${db_password}
      ME_CONFIG_MONGODB_URL: mongodb://${db_user}:${db_password}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
