import fs from "fs";

function file2commandName(file: string) {
    const fileNameWithoutExtension = file.replace(".ts", "");
    return {
        fileName: fileNameWithoutExtension,
        commandName: fileNameWithoutExtension.replace(
            /-([a-z])/g,
            (match, p1) => p1.toUpperCase()
        ),
    };
}

/**
 * This script generates the src/commands/index.ts file by reading all command files in the src/commands directory.
 * It creates import statements for each command file and exports them in a commands object.
 * To use this script, run 'npm run update:index' after adding or removing command files.
 */
function updateIndexFile() {
    const comment =
        "// This file is auto-generated by scripts/update-index.ts. Do not edit manually.\n" +
        "// To update this file, add or remove command files in the src/commands\n" +
        "// directory and run 'npm run update:index'.\n\n";

    const commandsDir = "./src/commands";
    const indexPath = `${commandsDir}/index.ts`;

    const commandFiles = fs
        .readdirSync(commandsDir)
        .filter((file) => file.endsWith(".ts") && file !== "index.ts")
        .map(file2commandName);

    const exportStatements = commandFiles.map((file) => {
        return `import * as ${file.commandName} from "./${file.fileName}";`;
    });

    const commandsExport = `\n\nexport const commands = {\n${commandFiles
        .map((file) => {
            return `    [${file.commandName}.data.name]: ${file.commandName},`;
        })
        .join("\n")}\n};`;

    const code = comment + exportStatements.join("\n") + commandsExport;

    fs.writeFileSync(indexPath, code);
    console.log("Updated commands/index.ts with the following commands:");
    commandFiles.forEach((file) => {
        console.log(`  - ${file.commandName}`);
    });
}

updateIndexFile();
