FROM node:lts-alpine

ENV NODE_ENV production

WORKDIR /bot

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

COPY . .

CMD npm start
